name: Movok Test Project (CI included) | © 2025 by haiha

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Verify Chrome version
      run: chrome --version

    - name: Run tests with Maven
      run: mvn -B clean test

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/surefire-reports/

# End of CI workflow file.
