# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Movok Test Project (CI included) | © 2025 by haiha

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'         # Sử dụng JDK 17 để tương thích tốt hơn với Selenium/TestNG
        distribution: 'temurin'
        cache: maven

    - name: Run tests with Maven
      run: mvn -B clean test     # Chạy test thay vì package, đảm bảo tạo báo cáo TestNG

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports        # Tên artifact là test-reports
        path: target/surefire-reports/  # Đường dẫn đến báo cáo test

# End of CI workflow file.
